# Target name
LIBNAME =

# Directories
OBJDIR = obj
SRCDIR = src
INCDIR = inc
LIBDIR = lib
DEPDIR = .d

include $(PROJBASE)/cm/global.mk
include $(PROJBASE)/cm/filter_code.mk
include $(PROJBASE)/cm/obj_rules.mk

# include 
INC += -I$(INCDIR) -I$(PROJBASE)/cm/log/inc

CFLAGS += -DDEBUG_CM

