# Target name
TARGET = add_demo

# Directories
OBJDIR = obj
SRCDIR = src
INCDIR = inc
LIBDIR = lib
DEPDIR = .d

include $(PROJBASE)/cm/global.mk
include $(PROJBASE)/cm/filter_code.mk
include $(PROJBASE)/cm/bin_rules.mk

# include
INC += -I$(PROJBASE)/cm/foundation/inc

# platform dependency

# compile flags

# link flags

# link c or cpp target
LD := $(CXX)

	