# Target name
LIBNAME = libads

# Directories
OBJDIR = obj
SRCDIR = src
INCDIR = inc
LIBDIR = lib
DEPDIR = .d

include $(PROJBASE)/cm/global.mk
include $(PROJBASE)/cm/filter_code.mk
include $(PROJBASE)/cm/lib_rules.mk

# include
INC += -I$(INCDIR) -I$(PROJBASE)/cm/foundation/inc -I$(PROJBASE)/cm/clog/inc -I$(PROJBASE)/cm/3pp/inc

# platform dependency

# compile flags
CFLAGS += -Wno-write-strings


